### ISSUE TITLE
Unexpected error messaged on invalid authentication

### ISSUE THREAD

**Issue by petermikitsh** [volfco/MyCoursesDownloader#12]
# Description

When authenticating with an invalid password, it's unclear why the process exits early.
# Actual Results

Authenticate using an invalid password, e.g.,

```
$ python3 mycoursesdownloader.py -u pam3961 -d mycourses
RIT Password: 
[2016-09-05 14:23:58.649104][ Warning] Directory does not exist. Creating
Traceback (most recent call last):
  File "mycoursesdownloader.py", line 167, in <module>
    "SAMLResponse": re.search('(<input type="hidden" name="SAMLResponse" value=").*("/>)', rs.text).group(0).replace('<input type="hidden" name="SAMLResponse" value="', '').replace('"/>', '')
AttributeError: 'NoneType' object has no attribute 'group'
```
# Expected Results

I expected a message explaining that my password was invalid before the process exited.

**Comment by vg** [comment]
I am getting the same error message. <strike>I am sure my password is correct as I am able to login through the web.</strike>  Oops. I was entering the wrong password. Sorry. 

```
RIT Password:
Traceback (most recent call last):
  File "mycoursesdownloader.py", line 167, in <module>
    "SAMLResponse": re.search('(<input type="hidden" name="SAMLResponse" value=").*("/>)', rs.text).group(0).replace('<input type="hidden" name="SAMLResponse" value="', '').replace('"/>', '')
AttributeError: 'NoneType' object has no attribute 'group'
```
